name: Daily Chromedriver Sync

on:
  schedule:
    # 每天北京时间 12 点运行 (UTC 4:00)
    - cron: '0 4 * * *'
  workflow_dispatch: # 允许你随时手动点击按钮测试

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 关键：赋予 Actions 机器人写入仓库的权限

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run Update Script
        id: sync_task
        run: python update_driver.py

      - name: Commit and Push Changes
        if: steps.sync_task.outputs.updated == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "${{ steps.sync_task.outputs.version }} version chromedriver"
          git push
